#==================================================================================================
# Xcodegen documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
#==================================================================================================

#==================================================================================================
name: RickyAndMorty
#==================================================================================================

settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "Apple Development"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"

options:
  xcodeVersion: "14.0"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "16.0"

configs:
  Debug: debug
  Release: release

#==================================================================================================
targets:
#==================================================================================================

#____________________________________________________________
# RickyAndMorty

  RickyAndMorty:

    platform: iOS
    type: application

    sources:
      - path: RickyAndMorty
        type: Group

    settings:
      CODE_SIGN_STYLE: "Automatic"
      #DEVELOPMENT_TEAM: "B7G6QF44XW"
      PRODUCT_BUNDLE_IDENTIFIER: com.viniciusalbino.RickyAndMorty
      INFOPLIST_FILE: RickyAndMorty/SupportingFiles/Info.plist

      ENABLE_BITCODE: "YES"

#____________________________________________________________
# Unit Tests

  RickyAndMortyTests:

    platform: iOS
    type: bundle.unit-test

    sources:
      - path: RickyAndMortyTests

    dependencies:
      - target: RickyAndMorty
#==================================================================================================
schemes:
#==================================================================================================

  Debug:
    build:
      targets:
        RickyAndMorty: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - RickyAndMorty
      targets:
        - RickyAndMortyTests

#==================================================================================================
